color : gree22n
hero : luban
api-package : com.waiwing.Shop.api

shop:
  security:
    jwt-key: dengweirong
    token-expired-in: 8640000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: com394053371
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true



